CC = gcc
CFLAGS = -Wall -g

tree: tree.c
	@echo making tree...
	@$(CC) $(CFLAGS) ../tree.c -o tree

bst: BST.c
	@echo making tree...
	@$(CC) $(CFLAGS) ../BST.c -o bst


clean:
	rm -f tree
	rm -f stack
	rm -f queue